### ISSUE TITLE
app can't handle existing tokenization

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-spacy-wrapper#25]
The app can't handle existing tokenization, and doing it's own tokenization all the time, effectively making the app useless in a pipeline setting. 
@marcverhagen can you take a look at this?

**Comment by marcverhagen** [comment]
I did look into this a while ago. spaCy always tokenizes, but it does allow you to write your own tokenizer. The thing is that at the time I did not see a clean way of how that tokenizer accesses the MMIF input and picks an existing tokenizer view to get the tokens from. The easiest way is probably for the application to write some temporary file with the tokenization and let the spaCy tokenizer read it.

Instead I added alignment code to the summarizer, which made it possible to trace named entities to timeframes, making sure that spaCy is not useless in a pipeline.

**Comment by keighrim** [comment]
spaCy does not always tokenize, and its behavior is well-documented in [the official documentation](https://spacy.io/api/doc). I have done this many times in the past (backing up to many years) and have had no problem with it. 

What's needed is simply to collect existing tokens in a list and cache their annotation_ids for later mapping, initialize a spacy pipeline, pass the list of tokens, and wrap the results back into MMIF format using cached token ids. 

Summarizer is not a CLAMS app, so I will still consider this app useless in a CLAMS pipeline setting. For example, MMIF-visualizer can't display what the summarizer returns, however beautifully it re-organizes tokens and entities and timeframes, etc.

**Comment by marcverhagen** [comment]
> What's needed is simply to collect existing tokens in a list and cache their annotation_ids for later mapping, initialize a spacy pipeline, pass the list of tokens, and wrap the results back into MMIF format using cached token ids.

Ah, yes, I stand corrected, using Doc() instead of nlp() would make that easy and I can add a parameter for that. There is a complication though in that NLP processing components start from TextDocuments and that will need to be fiddled with a bit.

> Summarizer is not a CLAMS app, so I will still consider this app useless in a CLAMS pipeline setting. For example, MMIF-visualizer can't display what the summarizer returns, however beautifully it re-organizes tokens and entities and timeframes, etc.

That's not a helpful statement because it is not useless, it just needs some processing, like the visualizer needs to do some processing to display things and that does not mean that the MMIF is useless.

**Comment by keighrim** [comment]
I guess my argument was poorly worded. I'll change it; the app (<=0.0.8) was useful only as a standalone app, and when it was used in a pipeline it added no additional value (compared to the standalone mode) but more technical burden for additional processing for downstream apps and consumers.

Anyway, fixed via #26. Closing the issue.
